### ISSUE TITLE
Binder link missing

### ISSUE THREAD

**Issue by henryiii** [pyhf/pyhf-tutorial#26]
The launch button seems to be missing for binder. Not sure why, config seems right on a first look-through.

**Comment by matthewfeickert** [comment]
@henryiii can you elaborate on what you mean by missing? I'm on a bus atm, but I can see it on mobile.

![image](https://user-images.githubusercontent.com/5142394/180502331-6a68e411-5fe1-4f02-9292-817dd3aadbfa.jpeg)

**Comment by henryiii** [comment]
Sorry, didn't specify this was for the JupyerBook. There should be a button on the top and it's missing.

**Comment by henryiii** [comment]
<img width="1311" alt="Screen Shot 2022-07-22 at 12 17 26 PM" src="https://user-images.githubusercontent.com/4616906/180510745-d70b7025-84fe-497a-86e8-e2b46b8cbfd3.png">

**Comment by matthewfeickert** [comment]
@henryiii Oh that's because the launch button only shows up on notebooks and the intro page is generated from a Markdown file. Go to any of the tutorial content pages generated from notebooks and it is there 

e.g. https://pyhf.github.io/pyhf-tutorial/HelloWorld.html

![image](https://user-images.githubusercontent.com/5142394/180514302-e04a121d-a52c-4c4b-ad5d-74092d6a26cf.jpeg)

**Comment by henryiii** [comment]
AHh, thanks! Doesn't quite make as much sense for JuptyerLab, but I see why it might that been done that way for JupyterBook when it was designed. Thanks!
